In [43]:
import pandas as pd
import numpy as np

###### Beispiele

In [44]:
df = pd.read_csv("../data/Library_Usage_withMembershipDuration.csv", low_memory=False)

In [45]:
df.columns

Index(['Unnamed: 0', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Definition',
       'Circulation Active Month', 'Circulation Active Year',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Within San Francisco County', 'is_adult',
       'log_renewals', 'Membership Duration'],
      dtype='object')

In [46]:
df.loc[df['Total Checkouts'] > 10000]

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
12694,12694,Senior,12233,5416,75 years and over,Merced,3.0,2024.0,Email,True,2003,False,False,8.597297,255.0
12925,12925,Senior,10428,1079,75 years and over,Ortega,3.0,2024.0,Email,True,2003,False,False,6.984716,255.0
54102,54102,Senior,17663,56,65 to 74 years,Marina,3.0,2024.0,Email,True,2008,False,False,4.043051,195.0
54414,54414,Senior,12675,1422,65 to 74 years,Chinatown,3.0,2024.0,Email,True,2003,False,False,7.260523,255.0
59475,59475,Senior,11252,2628,65 to 74 years,Main,3.0,2024.0,Phone,False,2013,True,False,7.874359,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293994,293994,Adult,39743,659,60 to 64 years,Ortega,3.0,2024.0,Email,True,2003,True,True,6.492240,255.0
294100,294100,Adult,10454,8663,35 to 44 years,Ortega,3.0,2024.0,Email,True,2003,True,True,9.066932,255.0
306622,306622,Adult,10065,3897,60 to 64 years,Golden Gate Valley,3.0,2024.0,Email,True,2003,True,True,8.268219,255.0
312053,312053,Adult,14825,3915,25 to 34 years,Park,3.0,2024.0,Email,True,2003,True,True,8.272826,255.0
328352,328352,Adult,12122,122,55 to 59 years,Bayview,3.0,2024.0,Email,True,2003,True,True,4.812184,255.0

In [47]:
# Alternative: Hilfsvariable erstellen, die den booleschen Vektor zwischenspeichert
row_filter = df['Total Checkouts'] > 10000
df.loc[row_filter]

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
12694,12694,Senior,12233,5416,75 years and over,Merced,3.0,2024.0,Email,True,2003,False,False,8.597297,255.0
12925,12925,Senior,10428,1079,75 years and over,Ortega,3.0,2024.0,Email,True,2003,False,False,6.984716,255.0
54102,54102,Senior,17663,56,65 to 74 years,Marina,3.0,2024.0,Email,True,2008,False,False,4.043051,195.0
54414,54414,Senior,12675,1422,65 to 74 years,Chinatown,3.0,2024.0,Email,True,2003,False,False,7.260523,255.0
59475,59475,Senior,11252,2628,65 to 74 years,Main,3.0,2024.0,Phone,False,2013,True,False,7.874359,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293994,293994,Adult,39743,659,60 to 64 years,Ortega,3.0,2024.0,Email,True,2003,True,True,6.492240,255.0
294100,294100,Adult,10454,8663,35 to 44 years,Ortega,3.0,2024.0,Email,True,2003,True,True,9.066932,255.0
306622,306622,Adult,10065,3897,60 to 64 years,Golden Gate Valley,3.0,2024.0,Email,True,2003,True,True,8.268219,255.0
312053,312053,Adult,14825,3915,25 to 34 years,Park,3.0,2024.0,Email,True,2003,True,True,8.272826,255.0
328352,328352,Adult,12122,122,55 to 59 years,Bayview,3.0,2024.0,Email,True,2003,True,True,4.812184,255.0

In [48]:
# Filter von Zeilen mit dem Wert 'Senior' in der Spalte 'Patron Type Definition' und dem Wert 'Email' in der Spalte 'Notice Preference Definition'
row_filter = (df['Patron Type Definition'] == 'Senior') & (df['Notice Preference Definition'] == 'Email')
df.loc[row_filter]

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
0,0,Senior,5,0,75 years and over,Main,11.0,2022.0,Email,True,2015,False,False,0.0,95.0
5,5,Senior,0,0,75 years and over,Main,4.0,2021.0,Email,True,2009,False,False,0.0,148.0
27,27,Senior,0,0,75 years and over,Main,10.0,2023.0,Email,True,2016,False,False,0.0,94.0
28,28,Senior,0,0,65 to 74 years,Main,3.0,2024.0,Email,True,2016,False,False,0.0,99.0
29,29,Senior,0,0,65 to 74 years,Main,8.0,2023.0,Email,True,2020,False,False,0.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450101,450101,Senior,0,0,75 years and over,Main,3.0,2024.0,Email,True,2013,False,False,0.0,135.0
450102,450102,Senior,0,0,65 to 74 years,Noe Valley,3.0,2024.0,Email,True,2019,False,False,0.0,63.0
450142,450142,Senior,0,0,65 to 74 years,Main,11.0,2022.0,Email,True,2021,Null,False,0.0,23.0
450143,450143,Senior,0,0,65 to 74 years,Main,3.0,2024.0,Email,True,2019,Null,False,0.0,63.0
450144,450144,Senior,1,0,75 years and over,Main,1.0,2024.0,Email,True,2015,Null,False,0.0,109.0

In [49]:
filter1 = (df['Total Checkouts'] >= 20) & (df['Total Checkouts'] <= 80)

In [50]:
filter1

0         False
1         False
2         False
3         False
4         False
          ...
450354    False
450355    False
450356    False
450357    False
450358    False
Name: Total Checkouts, Length: 450359, dtype: bool

In [51]:
filter2 =  df['Total Checkouts'].between(20, 80)

In [52]:
filter2

0         False
1         False
2         False
3         False
4         False
          ...
450354    False
450355    False
450356    False
450357    False
450358    False
Name: Total Checkouts, Length: 450359, dtype: bool

In [53]:
all(filter1 == filter2)

True

###### Aufgaben

In [54]:
df['Patron Type Definition'].unique()

array(['Senior', 'Adult', 'Welcome', 'Teacher Card', 'Juvenile', 'Teen',
       'Digital Access Card', 'At User Adult', 'Visitor', 'Retired Staff',
       'At User Teen', 'At User Senior', 'Library By Mail',
       'At User Welcome', 'At User Juvenile', 'Bibliocommons', 'Business'],
      dtype=object)

In [55]:
df.loc[df['Patron Type Definition'] == ("Juvenile" or "At User Juvenile")]

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
1487,1487,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,False,0.000000,0.0
1488,1488,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,False,0.000000,0.0
1489,1489,Juvenile,0,0,10 to 19 years,Main,NaN,NaN,Email,True,2021,False,False,0.000000,0.0
1490,1490,Juvenile,3,9,10 to 19 years,Main,3.0,2024.0,Email,True,2022,False,False,2.302585,27.0
1491,1491,Juvenile,0,0,0 to 9 years,Main,6.0,2023.0,Email,True,2017,False,False,0.000000,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450243,450243,Juvenile,0,0,10 to 19 years,Visitacion Valley,NaN,NaN,Email,False,2023,Null,False,0.000000,0.0
450244,450244,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,False,1.098612,10.0
450245,450245,Juvenile,0,0,0 to 9 years,Bayview,NaN,NaN,Email,False,2023,Null,False,0.000000,0.0
450246,450246,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,False,1.098612,10.0
450247,450247,Juvenile,11,15,0 to 9 years,Bayview,3.0,2022.0,Email,True,2022,Null,False,2.772589,3.0

In [56]:
# Filter: Kindern unter 10 Jahren
filter_kind10 = (df['Patron Type Definition'] == "Juvenile") & (df['Age Range'] == "0 to 9 years")

In [57]:
df.loc[filter_kind10]  # Anzahl EintrÃ¤ge: 33.013

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
1487,1487,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,False,0.000000,0.0
1488,1488,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,False,0.000000,0.0
1491,1491,Juvenile,0,0,0 to 9 years,Main,6.0,2023.0,Email,True,2017,False,False,0.000000,78.0
1493,1493,Juvenile,0,0,0 to 9 years,Main,3.0,2024.0,Email,True,2022,False,False,0.000000,27.0
1497,1497,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2022,False,False,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450241,450241,Juvenile,0,0,0 to 9 years,Bernal Heights,NaN,NaN,Email,True,2022,Null,False,0.000000,0.0
450244,450244,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,False,1.098612,10.0
450245,450245,Juvenile,0,0,0 to 9 years,Bayview,NaN,NaN,Email,False,2023,Null,False,0.000000,0.0
450246,450246,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,False,1.098612,10.0
450247,450247,Juvenile,11,15,0 to 9 years,Bayview,3.0,2022.0,Email,True,2022,Null,False,2.772589,3.0

In [59]:
# Gibt es Personen mit mehr als 20000 Ausleihen? 
df.loc[df['Total Checkouts'] > 20000]  # Es gibt sieben Personen

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
60282,60282,Senior,20561,1021,65 to 74 years,Main,3.0,2024.0,Phone,False,2004,True,False,6.929517,243.0
60622,60622,Senior,23134,617,65 to 74 years,Main,3.0,2024.0,Print,False,2003,True,False,6.426488,255.0
60994,60994,Senior,21890,16,75 years and over,Main,1.0,2023.0,Email,True,2005,True,False,2.833213,217.0
179460,179460,Adult,35176,62,25 to 34 years,Sunset,3.0,2024.0,Email,True,2010,True,True,4.143135,171.0
234329,234329,Adult,23345,6458,55 to 59 years,Chinatown,3.0,2024.0,Email,True,2003,True,True,8.773230,255.0
234381,234381,Adult,24386,387,45 to 54 years,Chinatown,3.0,2024.0,Phone,False,2003,True,True,5.961005,255.0
293994,293994,Adult,39743,659,60 to 64 years,Ortega,3.0,2024.0,Email,True,2003,True,True,6.492240,255.0

In [60]:
# Wie viele Personen stammen aus dem Stadtteil (Richmond)?
df.loc[df['Home Library Definition'] == "Richmond"]  # Es gibt 21.433 EintrÃ¤ge

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
3,3,Welcome,1,1,20 to 24 years,Richmond,8.0,2022.0,Email,True,2022,False,False,0.693147,8.0
228,228,Senior,0,0,65 to 74 years,Richmond,2.0,2024.0,Email,True,2016,False,False,0.000000,98.0
229,229,Senior,0,0,75 years and over,Richmond,2.0,2024.0,Email,True,2016,False,False,0.000000,98.0
230,230,Senior,7,19,65 to 74 years,Richmond,3.0,2024.0,Email,True,2023,False,False,2.995732,15.0
231,231,Senior,0,0,65 to 74 years,Richmond,1.0,2024.0,Email,True,2019,False,False,0.000000,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450159,450159,Adult,0,0,25 to 34 years,Richmond,NaN,NaN,Email,True,2023,Null,True,0.000000,0.0
450198,450198,Juvenile,0,0,10 to 19 years,Richmond,7.0,2023.0,Email,False,2023,Null,False,0.000000,7.0
450255,450255,Teen,1,0,20 to 24 years,Richmond,2.0,2024.0,Email,False,2023,Null,False,0.000000,14.0
450256,450256,Teen,1288,109,10 to 19 years,Richmond,8.0,2023.0,Email,True,2009,Null,False,4.700480,176.0
450291,450291,Digital Access Card,0,0,35 to 44 years,Richmond,4.0,2023.0,Email,False,2023,Null,False,0.000000,4.0

In [63]:
# Wie viele Prozent der Beobachtungen haben eine Membership Duration von Null Monaten?
df.loc[df['Membership Duration'] == 0] # Es gibt 40.317 EintrÃ¤ge

,Unnamed: 0,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,is_adult,log_renewals,Membership Duration
14,14,Teacher Card,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2023,False,False,0.0,0.0
17,17,Teacher Card,0,0,45 to 54 years,Main,NaN,NaN,Email,True,2020,False,False,0.0,0.0
36,36,Senior,0,0,65 to 74 years,Main,NaN,NaN,Email,True,2023,False,False,0.0,0.0
93,93,Senior,0,0,65 to 74 years,Main,NaN,NaN,Email,True,2023,False,False,0.0,0.0
127,127,Senior,0,0,65 to 74 years,Main,NaN,NaN,Email,True,2018,False,False,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450321,450321,Digital Access Card,0,0,60 to 64 years,Glen Park,NaN,NaN,Email,False,2023,Null,False,0.0,0.0
450324,450324,Digital Access Card,0,0,45 to 54 years,Glen Park,NaN,NaN,Email,False,2023,Null,False,0.0,0.0
450339,450339,Digital Access Card,0,0,75 years and over,Marina,NaN,NaN,Email,True,2022,Null,False,0.0,0.0
450340,450340,Digital Access Card,0,0,45 to 54 years,Marina,NaN,NaN,Email,True,2022,Null,False,0.0,0.0
450354,450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaN,NaN,Email,False,2023,Null,False,0.0,0.0

In [68]:
p_wert = len(df.loc[df['Membership Duration'] == 0])

In [69]:
p_wert

40317

In [70]:
g_wert = len(df['Membership Duration'])

In [71]:
g_wert

450359

In [72]:
prozent = (p_wert/g_wert) * 100

In [73]:
prozent

8.952191473913034

In [74]:
round(prozent, 2)

8.95